/**
 * Electronic Data Interchange API
 * EDI project API 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *//* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs';

import { ElectronicDataInterchangeAPIClassesResponse1ElectronicDataInterchangeAPIClassesAutenticacionSesionConsultaMapaRiesgoAPIVersion1000CultureneutralPublicKeyTokennull } from '../model/electronicDataInterchangeAPIClassesResponse1ElectronicDataInterchangeAPIClassesAutenticacionSesionConsultaMapaRiesgoAPIVersion1000CultureneutralPublicKeyTokennull';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class AuthenticationService {

    protected basePath = '/';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param username 
     * @param password 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public apiAuthenticationAuthenticatePost(username?: string, password?: string, observe?: 'body', reportProgress?: boolean): Observable<ElectronicDataInterchangeAPIClassesResponse1ElectronicDataInterchangeAPIClassesAutenticacionSesionConsultaMapaRiesgoAPIVersion1000CultureneutralPublicKeyTokennull>;
    public apiAuthenticationAuthenticatePost(username?: string, password?: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<ElectronicDataInterchangeAPIClassesResponse1ElectronicDataInterchangeAPIClassesAutenticacionSesionConsultaMapaRiesgoAPIVersion1000CultureneutralPublicKeyTokennull>>;
    public apiAuthenticationAuthenticatePost(username?: string, password?: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<ElectronicDataInterchangeAPIClassesResponse1ElectronicDataInterchangeAPIClassesAutenticacionSesionConsultaMapaRiesgoAPIVersion1000CultureneutralPublicKeyTokennull>>;
    public apiAuthenticationAuthenticatePost(username?: string, password?: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {



        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (username !== undefined && username !== null) {
            queryParameters = queryParameters.set('username', <any>username);
        }
        if (password !== undefined && password !== null) {
            queryParameters = queryParameters.set('password', <any>password);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'text/plain',
            'application/json',
            'text/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.request<ElectronicDataInterchangeAPIClassesResponse1ElectronicDataInterchangeAPIClassesAutenticacionSesionConsultaMapaRiesgoAPIVersion1000CultureneutralPublicKeyTokennull>('post',`${this.basePath}/api/Authentication/Authenticate`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
