/**
 * Electronic Data Interchange API
 * EDI project API 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface ElectronicDataInterchangeAPIClassesAutenticacionSesionConsulta { 
    idUsuario?: number;
    idEmpresa?: number;
    idEmpresaExterno?: number;
    token?: string;
    fechaInicio?: Date;
    ultimaActividad?: Date;
    navegador?: string;
}