/**
 * Electronic Data Interchange API
 * EDI project API 
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { ElectronicDataInterchangeAPIClassesAutenticacionSesionConsulta } from './electronicDataInterchangeAPIClassesAutenticacionSesionConsulta';

export interface ElectronicDataInterchangeAPIClassesResponse1ElectronicDataInterchangeAPIClassesAutenticacionSesionConsultaMapaRiesgoAPIVersion1000CultureneutralPublicKeyTokennull { 
    id?: number;
    status?: number;
    message?: string;
    hasError?: boolean;
    data?: ElectronicDataInterchangeAPIClassesAutenticacionSesionConsulta;
}